name: Mobile Build
on:
  workflow_call:
    inputs:
      publish_artifacts:
        description: "Publish artifacts"
        required: false
        type: boolean
        default: false

jobs:
  # output will be there backend/user-node/ios/libs/*
  ios:
    name: IOS build
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v3
        with:
          path: backend/user-node/ios/libs/libgmp.a
          key: ${{ runner.os }}-libgmp

      - name: Build libgmp
        run: |
          set -eu
          if [[ ! -f "backend/user-node/ios/libs/libgmp.a" ]]; then
            ./backend/user-node/ios/build-libgmp.sh
          fi
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: aarch64-apple-ios, x86_64-apple-ios
          toolchain: 1.75.0
      - name: Build libguardian
        run: |
          set -eu
          ./backend/user-node/ios/build-libguardian.sh
          ./backend/user-node/ios/zip-library.sh libguardian
      - name: Upload libguardian
        if: inputs.publish_artifacts == true
        uses: actions/upload-artifact@v3
        with:
          name: libguardian.tar.gz
          path: backend/user-node/ios/libguardian.tar.gz
          retention-days: 30
  # output will be there backend/user-node/android/libs/*
  android:
    name: Android build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v3
        with:
          path: backend/user-node/android/libs/**/libgmp.so
          key: ${{ runner.os }}-libgmp

      - name: Build libgmp
        run: |
          set -eu -o pipefail
          ./backend/user-node/android/download-libgmp.sh --release
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android
          toolchain: 1.75.0
      - name: Build libnode
        env:
          ANDROID_API: 29
        run: |
          set -eu -o pipefail
          ./backend/user-node/android/build-libnode.sh --release
          ./backend/user-node/android/zip-library.sh libnode
      - name: Upload libnode
        if: inputs.publish_artifacts == true
        uses: actions/upload-artifact@v3
        with:
          name: libnode.tar.gz
          path: backend/user-node/android/libnode.tar.gz
          retention-days: 30
